### ISSUE TITLE
HPM Monitor Studio elf文件支持

### ISSUE THREAD

**Issue by Lyubiao** [hpmicro/hpm_apps#2]
我移植了hpm monitor到其他cortex-m的芯片平台；hpm monitor studio已经可以正确读取到版本了；但是导入elf文件的时候提示报错，hpm monitor studio是否不支持gcc或者armcc输出的elf文件
![image](https://github.com/user-attachments/assets/7792736a-b460-4e76-b5c3-146a65ad5b8a)

**Comment by sakumisu** [comment]
未经授权禁止使用到非 hpm 芯片，谢谢，否则将追究你的责任。
